### PR TITLE
Aishwarya

### PR DESCRIPTION
**Pull request by Aishwaryabhootra**

### CODE REVIEW

**Comment by priteshkulshreshtha** [comment]
Hey,

You have made pull request at the wrong repository. Just repeat what you did here at the 'git-task' repository.
Happy Coding.

**Comment by Aishwaryabhootra** [comment]
Can you please elaborate what I have to do now?  With Regards Aishwarya BhootraSent from Mail for Windows 10 From: priteshkulshreshthaSent: 23 December 2020 20:20To: 30DaysofWebDEV/DSC-30-Days-of-WebCc: Aishwaryabhootra; AuthorSubject: Re: [30DaysofWebDEV/DSC-30-Days-of-Web] Aishwarya (#8) Hey,You have made pull request at the wrong repository. Just repeat what you did here at the 'git-task' repository.Happy Coding.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by priteshkulshreshtha** [comment]
Had a hard time reading your comment.

> Can you please elaborate what I have to do now?

If you're asking about this. You need to make the Pull request in the [git_task](https://github.com/30DaysofWebDEV/git-task) repo (Click on the name to open it).

**Comment by Aishwaryabhootra** [comment]
Okk, I will do it.
Thankyou
I am sorry for the trouble since I am new to github.

**Comment by Aishwaryabhootra** [comment]
I have done it again.
Can you please check and update me is it right now?

**Comment by priteshkulshreshtha** [comment]
Looks fine.

**Pull request closed without merging**
